language: node_js
env: NODE_ENV=test
node_js:
  - "0.10"
before_install: gem install sass
install:
  - npm install phantomjs -g
  - npm install casperjs -g
  - npm install gulp
  - npm install bower
  - git config --global url."https://".insteadOf git://
  - bower install
  - npm install
before_script:
  - phantomjs --version
  - casperjs --version
  - gulp &
  - sleep 20 # give gulp background task some time to execute.
script:
  - casperjs test public/js/test/casper.js
  - phantomjs run_jasmine.js http://localhost:1987/test