language: node_js
node_js:
  - "0.10"
before_install: gem install sass
install:
  - npm install phantomjs -g
  - npm install casperjs -g
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install
before_script:
  - phantomjs --version
  - casperjs --version
  - grunt &
  - sleep 5 # give grunt background task some time to execute.
script:
  - casperjs test build/features.js
  - phantomjs run_jasmine.js http://localhost:4000/SpecRunner.html